Add release please feature
googleapis/google-cloud-node pull request #3384
Opened 2022-10-03 20:00 UTC by sofisl

2022-10-03 20:16 UTC, bcoe approved these changes

2022-10-04 00:33 UTC, sofisl commented
@chingor13, do you know why the config schema is still failing? I thought we updated [here](https://github.com/googleapis/release-please/blob/df627b3bfc61cce25bcdc54ef7c282019479754a/schemas/config.json#L199) and [here](https://github.com/googleapis/repo-automation-bots/blob/44e97c5152bf4ee8c52520eca3a294d9c04a15a8/packages/release-please/src/config-schema.json#L112).

2022-10-05 18:54 UTC, chingor13 requested changes

2022-10-05 18:54 UTC, chingor13 commented on .github/release-please.yml
> +initialVersion: '0.1.0'
This isn't going to work if you're using `manifest: true`. It's going to read config values from the manifest config, not here.

2022-10-05 19:00 UTC, chingor13 requested changes

2022-10-11 18:41 UTC, tmatsuo commented
The schema file uses camelcase:

https://github.com/googleapis/repo-automation-bots/blob/cbc0d8f7a6a1c10df027d3ad046c2463d770dd97/packages/release-please/src/config-schema.json#L112

Have you tried camelcase like:

```
  "releaseType": "node",
  "initialVersion": "0.1.0"
}
```
?

2022-10-13 17:53 UTC, chingor13 approved these changes

2022-10-13 18:04 UTC, merged