fix: readme generation, do not fail if product documentation does not exist
googleapis/google-cloud-node pull request #3474
Opened 2022-11-02 01:38 UTC by sofisl

Fixes #3387

2022-11-02 21:03 UTC, bcoe requested changes

2022-11-02 21:03 UTC, bcoe commented on bin/generate-readme.mjs
> +      } catch (err) {
I would look at the error `code` and only set `remoteUrlExists = false` if the error returned is a 404 (indicating that it doesn't exist).

This way we don't mess up the README.md if there happen to be spurious 500s.

2022-11-04 20:23 UTC, alexander-fenster commented on bin/generate-readme.mjs
> +      if (!supportDocsUrl.match(/https/)) {
Let's do `/^https:/` to avoid possible matches in the middle of the string.

2022-11-04 20:23 UTC, alexander-fenster approved these changes

2022-11-04 23:27 UTC, merged