build: grab latest version of cloudrad
googleapis/google-cloud-node pull request #3677
Opened 2022-11-22 18:59 UTC by sofisl

2022-11-22 19:15 UTC, bcoe commented on .kokoro/release/docs-devsite-single.sh
> +npx @google-cloud/cloud-rad
```suggestion
npx @google-cloud/cloud-rad@0.2.18
```

2022-11-22 19:16 UTC, bcoe requested changes
I think it would still be good to pin to a version of `@google-cloud/cloud-rad`, otherwise if there are major changes to cloud-rad in the future our builds will break.

2022-11-22 19:20 UTC, dansaadati commented on .kokoro/release/docs-devsite-single.sh
> +npx @google-cloud/cloud-rad
Just published latest `npx @google-cloud/cloud-rad@0.2.18`

2022-11-28 19:37 UTC, bcoe approved these changes

2022-11-30 03:53 UTC, merged